import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar";
import { links } from "./data/links";
import { Footer } from "./components/footer";
import TopBarStats from "./components/top-section";
import { Roboto } from 'next/font/google'
import NewsTicker from "./components/fading-text";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotto = Roboto({
  variable: "--font-robotto-sans",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headlines = [
    "Bitcoin hits $30,000",
    "Ethereum 2.0 upgrade completed",
    "Ripple wins court case against SEC",
    "Binance launches new trading platform",
    "Coinbase adds support for new altcoin",
  ];
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} ${robotto.variable} font-geist antialiased`}
      >
        <div className="max-w-screen-xl mx-auto px-4">
          <TopBarStats />
          <NewsTicker headlines={headlines} speed={30} />

          <Navbar links={links} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );

}
